image: node:20

variables:
  PNPM_STORE_DIR: .pnpm-store

stages:
  - test
  - build
  - publish

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules/

.pnpm-install:
  before_script:
    - npm install -g pnpm
    - pnpm config set store-dir $PNPM_STORE_DIR
    - pnpm install --frozen-lockfile

test:
  extends: .pnpm-install
  stage: test
  script:
    - pnpm run lint
    - pnpm run test

build:
  extends: .pnpm-install
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist/

publish:
  extends: .pnpm-install
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - pnpm publish --no-git-checks
  rules:
    - if: $CI_COMMIT_TAG
