image: node:20

variables:
  PNPM_STORE_DIR: .pnpm-store

stages:
  - build
  - deploy

.pnpm-install:
  before_script:
    - npm install -g pnpm
    - pnpm config set store-dir $PNPM_STORE_DIR
    - pnpm install --frozen-lockfile

## Package
build:
  extends: .pnpm-install
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist/

publish:
  extends: .pnpm-install
  stage: deploy
  script:
    - echo "@firstbase:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - pnpm publish --no-git-checks
  rules:
    - if: $CI_COMMIT_TAG

## Storybook
build::storybook:
  stage: build
  script:
    - npm run build-storybook
  artifacts:
    paths:
      - storybook-static/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy::storybook:
  stage: deploy
  script:
    - mv storybook-static public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
