export { default as Badge } from './badge/Badge.vue'
export { default as Button } from './button/Button.vue'
export { default as Input } from './input-2/Input-old.vue'
export { default as Label } from './label-2/Label.vue'
export { default as Spinner } from './Spinner/Spinner.vue'
export { default as Tooltip } from './tooltip/Tooltip.vue'

export { FieldDescription } from './form-2/field-description'
export { FieldError } from './form-2/field-error'
export { default as Field } from './form-2/field/Field.vue'
export { InfoIcon } from './info-icon'
